### ISSUE TITLE
Question: .NET Framework 4.8

### ISSUE THREAD

**Issue by ns6000** [Cysharp/MessagePipe#96]
Hey, this is not an issue, just question.

Would it be possible to do IPC using MessagePipe between .NET 5/6/... client/server and .NET Framework 4.8 server/client? It should be possible because there is .NET Standard 2.0 implementation. But i'm not really sure how would the initialization be done, because i'm using DI only since .NET Core days and not in Framework applications. Is there some kind of example if it's possible?

**Comment by perennialmind** [comment]
It sounds like you're asking about IPC, since combining .Net 6 and .Net Framework runtimes in the same process is not supported. Happily, several [IPC flavors](https://github.com/Cysharp/MessagePipe#interprocesspubsub-iremoteasyncrequest--messagepipeinterprocess) are available via `MessagePipe.Interprocess` which supports your targets. I'd suggest named pipes.

**Comment by ns6000** [comment]
Actually, i tinkered with it, never made it to work, abandoned it and did it in SignalR...
